### ISSUE TITLE
Upgrade enonic in brew to 1.0.2

### ISSUE THREAD

**Issue by jsi** [enonic/homebrew-cli#2]

**Comment by jsi** [comment]
<img width="708" alt="Screenshot 2019-05-13 15 17 37" src="https://user-images.githubusercontent.com/477453/57624512-657ee200-7592-11e9-8595-8c1222de78fd.png">

Upgrading to v1.0.2 is not working on Mac.

**Comment by sigdestad** [comment]
Vi har 1.0.4 live nå, og det funket fint å gå fra 1.0.3. Lukker saken

**Comment by jsi** [comment]
Problemet i skjermdumpen ovenfor, hadde med søppel som lå igjen på min egen maskin, fra registreringen av PRen som ble avslått av brew.  -  Nå har jeg fått det til å funke, men det blir vel feil å lukke saken.  Den er løst, og da skal den med i statsen vår.  Alan lukker den i morgen.
